config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :my_models

  root 'my_models#index'

end

app/models/my_model.rb
class MyModel < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/my_models_controller.rb
class MyModelsController < ApplicationController
  before_action :set_my_model, only: [:show, :edit, :update, :destroy]

  # GET /my_models
  # GET /my_models.json
  def index
    @my_models = MyModel.all
  end

  # GET /my_models/1
  # GET /my_models/1.json
  def show
  end

  # GET /my_models/new
  def new
    @my_model = MyModel.new
  end

  # GET /my_models/1/edit
  def edit
  end

  # POST /my_models
  # POST /my_models.json
  def create
    @my_model = MyModel.new(my_model_params)

    respond_to do |format|
      if @my_model.save
        format.html { redirect_to @my_model, notice: 'My model was successfully created.' }
        format.json { render :show, status: :created, location: @my_model }
      else
        format.html { render :new }
        format.json { render json: @my_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_models/1
  # PATCH/PUT /my_models/1.json
  def update
    respond_to do |format|
      if @my_model.update(my_model_params)
        format.html { redirect_to @my_model, notice: 'My model was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_model }
      else
        format.html { render :edit }
        format.json { render json: @my_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_models/1
  # DELETE /my_models/1.json
  def destroy
    @my_model.destroy
    respond_to do |format|
      format.html { redirect_to my_models_url, notice: 'My model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_model
      @my_model = MyModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_model_params
      params.require(:my_model).permit(:name, :tipousuario, :reputacao, :rank, :level, :patente)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_models_helper.rb
module MyModelsHelper
end

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
         
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
             
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/my_models/_form.html.erb
<%= form_for(@my_model) do |f| %>
  <% if @my_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_model.errors.count, "error") %> prohibited this my_model from being saved:</h2>

      <ul>
      <% @my_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tipousuario %><br>
    <%= f.text_field :tipousuario %>
  </div>
  <div class="field">
    <%= f.label :reputacao %><br>
    <%= f.number_field :reputacao %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :patente %><br>
    <%= f.text_field :patente %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_models/edit.html.erb
<h1>Editing My Model</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_model %> |
<%= link_to 'Back', my_models_path %>

app/views/my_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing My Models</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tipousuario</th>
      <th>Reputacao</th>
      <th>Rank</th>
      <th>Level</th>
      <th>Patente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_models.each do |my_model| %>
      <tr>
        <td><%= my_model.name %></td>
        <td><%= my_model.tipousuario %></td>
        <td><%= my_model.reputacao %></td>
        <td><%= my_model.rank %></td>
        <td><%= my_model.level %></td>
        <td><%= my_model.patente %></td>
        <td><%= link_to 'Show', my_model %></td>
        <td><%= link_to 'Edit', edit_my_model_path(my_model) %></td>
        <td><%= link_to 'Destroy', my_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My model', new_my_model_path %>

app/views/my_models/new.html.erb
<h1>New My Model</h1>

<%= render 'form' %>

<%= link_to 'Back', my_models_path %>

app/views/my_models/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @my_model.name %>
</p>

<p>
  <strong>Tipousuario:</strong>
  <%= @my_model.tipousuario %>
</p>

<p>
  <strong>Reputacao:</strong>
  <%= @my_model.reputacao %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @my_model.rank %>
</p>

<p>
  <strong>Level:</strong>
  <%= @my_model.level %>
</p>

<p>
  <strong>Patente:</strong>
  <%= @my_model.patente %>
</p>

<%= link_to 'Edit', edit_my_model_path(@my_model) %> |
<%= link_to 'Back', my_models_path %>